create_dropout_database <-
function(co_ies,tipo_evasao){
	dbGetQuery(con,paste0("	
	with enem_empilhado as (
		--Select do ENEM 2014		
			SELECT
			nu_ano,
			nu_cpf,
			id_inscricao,
			id_mascara,
			in_estuda_classe_hospitalar,
			cod_municipio_residencia,
			cod_municipio_esc,
			id_dependencia_adm_esc,
			id_localizacao_esc,
			sit_func_esc,
			idade,
			tp_sexo,
			nacionalidade,
			cod_municipio_nascimento,
			st_conclusao,
			ano_concluiu,
			tp_escola,
			in_tp_ensino,
			tp_estado_civil,
			tp_cor_raca,
			in_baixa_visao,
			in_cegueira,
			in_surdez,
			in_deficiencia_auditiva,
			in_surdo_cegueira,
			in_deficiencia_fisica,
			in_deficiencia_mental,
			in_deficit_atencao,
			in_dislexia,
			in_gestante,
			in_lactante,
			in_idoso,
			in_autismo,
			in_sabatista,
			in_braille,
			in_ampliada_24,
			in_ampliada_18,
			in_ledor,
			in_acesso,
			in_transcricao,
			in_libras,
			in_leitura_labial,
			in_mesa_cadeira_rodas,
			in_mesa_cadeira_separada,
			in_guia_interprete,
			in_certificado,
			cod_municipio_prova,
			nota_cn,
			nota_ch,
			nota_lc,
			nota_mt,
			nu_nota_comp1,
			nu_nota_comp2,
			nu_nota_comp3,
			nu_nota_comp4,
			nu_nota_comp5,
			nu_nota_redacao,
			q001,
			q002,
			q003,
			q004,
			q005,
			q006,
			q007,
			q008,
			q009,
			q010,
			q011,
			q012,
			q013,
			q014,
			q015,
			q016,
			q017,
			q018,
			q019,
			q020,
			q021,
			q022,
			q023,
			q024,
			q025,
			q026,
			q027,
			q028,
			q029,
			q030,
			q031,
			q032,
			q033,
			q034,
			q035,
			q036,
			q037,
			q038,
			q039,
			q040,
			q041,
			q042,
			q043,
			q044,
			q045,
			q046,
			q047,
			q048,
			q049,
			q050,
			q051,
			q052,
			q053,
			q054,
			q055,
			q056,
			q057,
			q058,
			q059,
			q060,
			q061,
			q062,
			q063,
			q064,
			q065,
			q066,
			q067,
			q068,
			q069,
			q070,
			q071,
			q072,
			q073,
			q074,
			q075,
			q076
			FROM enem_2014
			WHERE nota_cn is not null and nota_ch is not null and nota_lc is not null and nota_mt is not null and nu_nota_comp1 is not null and nu_nota_comp2 is not null and nu_nota_comp3 is not null and nu_nota_comp4 is not null and nu_nota_comp5 is not null and nu_nota_redacao is not null

			UNION ALL

		--Select do ENEM 2013
			SELECT
			nu_ano,
			nu_cpf,
			id_inscricao,
			id_mascara,
			in_estuda_classe_hospitalar,
			cod_municipio_residencia,
			cod_municipio_esc,
			id_dependencia_adm_esc,
			id_localizacao_esc,
			sit_func_esc,
			idade,
			tp_sexo,
			nacionalidade,
			cod_municipio_nascimento,
			st_conclusao,
			ano_concluiu,
			tp_escola,
			in_tp_ensino,
			tp_estado_civil,
			tp_cor_raca,
			in_baixa_visao,
			in_cegueira,
			in_surdez,
			in_deficiencia_auditiva,
			in_surdo_cegueira,
			in_deficiencia_fisica,
			in_deficiencia_mental,
			in_deficit_atencao,
			in_dislexia,
			in_gestante,
			in_lactante,
			in_idoso,
			in_autismo,
			in_sabatista,
			in_braille,
			in_ampliada_24,
			in_ampliada_18,
			in_ledor,
			in_acesso,
			in_transcricao,
			in_libras,
			in_leitura_labial,
			in_mesa_cadeira_rodas,
			in_mesa_cadeira_separada,
			in_guia_interprete,
			in_certificado,
			cod_municipio_prova,
			nota_cn,
			nota_ch,
			nota_lc,
			nota_mt,
			nu_nota_comp1,
			nu_nota_comp2,
			nu_nota_comp3,
			nu_nota_comp4,
			nu_nota_comp5,
			nu_nota_redacao,
			q001,
			q002,
			q003,
			q004,
			q005,
			q006,
			q007,
			q008,
			q009,
			q010,
			q011,
			q012,
			q013,
			q014,
			q015,
			q016,
			q017,
			q018,
			q019,
			q020,
			q021,
			q022,
			q023,
			q024,
			q025,
			q026,
			q027,
			q028,
			q029,
			q030,
			q031,
			q032,
			q033,
			q034,
			q035,
			q036,
			q037,
			q038,
			q039,
			q040,
			q041,
			q042,
			q043,
			q044,
			q045,
			q046,
			q047,
			q048,
			q049,
			q050,
			q051,
			q052,
			q053,
			q054,
			q055,
			q056,
			q057,
			q058,
			q059,
			q060,
			q061,
			q062,
			q063,
			q064,
			q065,
			q066,
			q067,
			q068,
			q069,
			q070,
			q071,
			q072,
			q073,
			q074,
			q075,
			q076
			FROM enem_2013
			WHERE nota_cn is not null and nota_ch is not null and nota_lc is not null and nota_mt is not null and nu_nota_comp1 is not null and nu_nota_comp2 is not null and nu_nota_comp3 is not null and nu_nota_comp4 is not null and nu_nota_comp5 is not null and nu_nota_redacao is not null

			UNION ALL

		--Select do ENEM 2012
			SELECT	
			nu_ano,
			nu_cpf,
			id_inscricao,
			id_mascara,
			in_estuda_classe_hospitalar,
			cod_municipio_residencia,
			cod_municipio_esc,
			id_dependencia_adm_esc,
			id_localizacao_esc,
			sit_func_esc,
			idade,
			tp_sexo,
			NULL as nacionalidade,
			NULL as cod_municipio_nascimento,
			st_conclusao,
			ano_concluiu,
			tp_escola,
			in_tp_ensino,
			tp_estado_civil,
			tp_cor_raca,
			in_baixa_visao,
			in_cegueira,
			in_surdez,
			in_deficiencia_auditiva,
			in_surdo_cegueira,
			in_deficiencia_fisica,
			in_deficiencia_mental,
			in_deficit_atencao,
			in_dislexia,
			in_gestante,
			in_lactante,
			in_idoso,
			in_autismo,
			in_sabatista,
			in_braille,
			in_ampliada_24,
			in_ampliada_18,
			in_ledor,
			in_acesso,
			in_transcricao,
			in_libras,
			in_leitura_labial,
			in_mesa_cadeira_rodas,
			in_mesa_cadeira_separada,
			in_guia_interprete,
			in_certificado,
			cod_municipio_prova,
			nota_cn,
			nota_ch,
			nota_lc,
			nota_mt,
			nu_nota_comp1,
			nu_nota_comp2,
			nu_nota_comp3,
			nu_nota_comp4,
			nu_nota_comp5,
			nu_nota_redacao,
			Q01 as q001,
			Q02 as q002,
			Q03 as q003,
			Q04 as q004,
			Q05 as q005,
			Q06 as q006,
			Q07 as q007,
			Q08 as q008,
			Q09 as q009,
			Q10 as q010,
			Q11 as q011,
			Q12 as q012,
			Q13 as q013,
			Q14 as q014,
			Q15 as q015,
			Q16 as q016,
			Q17 as q017,
			Q18 as q018,
			Q19 as q019,
			Q20 as q020,
			Q21 as q021,
			case when Q22='B' then 'C' else Q22 end as q022,
			Q23 as q023,
			Q24 as q024,
			Q25 as q025,
			Q26 as q026,
			Q27 as q027,
			Q28 as q028,
			Q29 as q029,
			Q30 as q030,
			Q31 as q031,
			Q32 as q032,
			Q33 as q033,
			Q34 as q034,
			Q35 as q035,
			Q36 as q036,
			Q37 as q037,
			Q38 as q038,
			Q39 as q039,
			NULL as q040,
			NULL as q041,
			NULL as q042,
			NULL as q043,
			NULL as q044,
			NULL as q045,
			NULL as q046,
			NULL as q047,
			NULL as q048,
			NULL as q049,
			NULL as q050,
			NULL as q051,
			NULL as q052,
			NULL as q053,
			Q40 as q054,
			Q41 as q055,
			Q42 as q056,
			Q43 as q057,
			Q44 as q058,
			Q45 as q059,
			Q46 as q060,
			Q47 as q061,
			Q48 as q062,
			Q49 as q063,
			Q50 as q064,
			Q51 as q065,
			Q52 as q066,
			Q53 as q067,
			Q54 as q068,
			Q55 as q069,
			Q56 as q070,
			Q57 as q071,
			Q58 as q072,
			Q59 as q073,
			Q60 as q074,
			Q61 as q075,
			Q62 as q076
			FROM enem_2012
			WHERE nota_cn is not null and nota_ch is not null and nota_lc is not null and nota_mt is not null and nu_nota_comp1 is not null and nu_nota_comp2 is not null and nu_nota_comp3 is not null and nu_nota_comp4 is not null and nu_nota_comp5 is not null and nu_nota_redacao is not null

			UNION ALL

		--Select do ENEM 2011
			SELECT
			nu_ano,
			nu_cpf,
			id_inscricao,
			id_mascara,
			in_estuda_classe_hospitalar,
			cod_municipio_residencia,
			cod_municipio_esc,
			id_dependencia_adm_esc,
			id_localizacao_esc,
			sit_func_esc,
			idade,
			tp_sexo,
			NULL as nacionalidade,
			NULL as cod_municipio_nascimento,
			st_conclusao,
			ano_concluiu,
			tp_escola,
			in_tp_ensino,
			tp_estado_civil,
			tp_cor_raca,
			in_baixa_visao,
			in_cegueira,
			in_surdez,
			in_deficiencia_auditiva,
			in_surdo_cegueira,
			in_deficiencia_fisica,
			in_deficiencia_mental,
			in_deficit_atencao,
			in_dislexia,
			in_gestante,
			in_lactante,
			in_idoso,
			in_autismo,
			in_sabatista,
			in_braille,
			in_ampliada_24,
			in_ampliada_18,
			in_ledor,
			in_acesso,
			in_transcricao,
			in_libras,
			in_leitura_labial,
			in_mesa_cadeira_rodas,
			in_mesa_cadeira_separada,
			in_guia_interprete,
			in_certificado,
			cod_municipio_prova,
			nota_cn,
			nota_ch,
			nota_lc,
			nota_mt,
			nu_nota_comp1,
			nu_nota_comp2,
			nu_nota_comp3,
			nu_nota_comp4,
			nu_nota_comp5,
			nu_nota_redacao,
			q02 as q001,
			q03 as q002,
			NULL as q003,
			cast(q01 as numeric) as q004,
			q06 as q005,
			q07 as q006,
			q61 as q007,
			q62 as q008, 
			q63 as q009, 
			q64 as q010, 
			q65 as q011, 
			q66 as q012, 
			q67 as q013, 
			q68 as q014, 
			q69 as q015, 
			q70 as q016, 
			q71 as q017, 
			q72 as q018, 
			q73 as q019, 
			q74 as q020, 
			q75 as q021, 
			case when q08='B' then 'C' else q08 end as q022,
			cast(q24 as numeric) as q023,
			NULL as q024,
			NULL as q025,
			NULL as q026,
			NULL as q027,
			cast(q27 as numeric) as q028,
			NULL as q029,
			q28 as q030,
			q29 as q031,
			q30 as q032,
			q31 as q033,
			q32 as q034,
			q33 as q035,
			q58 as q036,
			q59 as q037,
			q60 as q038,
			q57 as q039,
			cast(case when q23=' .' then NULL else q23 end as numeric) as q040,
			q22 as q041,
			cast(case when q09=' ' then NULL else q09 end as numeric) as q042,
			cast(case when q10=' ' then NULL else q10 end as numeric) as q043,
			cast(case when q11=' ' then NULL else q11 end as numeric) as q044,
			cast(case when q12=' ' then NULL else q12 end as numeric) as q045,
			cast(case when q13=' ' then NULL else q13 end as numeric) as q046,
			q15 as q047,
			q16 as q048,
			q17 as q049,
			q18 as q050,
			q19 as q051,
			q20 as q052,
			q21 as q053,
			q34 as q054,
			q35 as q055,
			q36 as q056,
			q37 as q057,
			q38 as q058,
			q39 as q059,
			q40 as q060,
			q41 as q061,
			NULL as q062,
			NULL as q063,
			q43 as q064,
			case when q44 in ('0','1','2') then 'A' when q44 in ('3','4','5') then 'B' else NULL end as q065,
			case when q45 in ('0','1','2') then 'A' when q45 in ('3','4','5') then 'B' else NULL end as q066,
			NULL as q067,
			case when q46 in ('0','1','2') then 'A' when q46 in ('3','4','5') then 'B' else NULL end as q068,
			NULL as q069,
			case when q47 in ('0','1','2') then 'A' when q47 in ('3','4','5') then 'B' else NULL end as q070,
			case when q48 in ('0','1','2') then 'A' when q48 in ('3','4','5') then 'B' else NULL end as q071,
			case when q49 in ('0','1','2') then 'A' when q49 in ('3','4','5') then 'B' else NULL end as q072,
			case when q50 in ('0','1','2') then 'A' when q50 in ('3','4','5') then 'B' else NULL end as q073,
			case when q51 in ('0','1','2') then 'A' when q51 in ('3','4','5') then 'B' else NULL end as q074,
			NULL as q075,
			q52 as q076
			FROM enem_2011_comp
			WHERE nota_cn is not null and nota_ch is not null and nota_lc is not null and nota_mt is not null and nu_nota_comp1 is not null and nu_nota_comp2 is not null and nu_nota_comp3 is not null and nu_nota_comp4 is not null and nu_nota_comp5 is not null and nu_nota_redacao is not null

			UNION ALL

		--Select do ENEM 2010
			SELECT
			nu_ano,
			nu_cpf,
			id_inscricao,
			id_mascara,
			in_estuda_classe_hospitalar,
			cod_municipio_residencia,
			cod_municipio_esc,
			id_dependencia_adm_esc,
			id_localizacao_esc,
			sit_func_esc,
			idade,
			tp_sexo,
		    NULL as nacionalidade,
			NULL as cod_municipio_nascimento,
			st_conclusao,
			ano_concluiu,
			tp_escola,
			in_tp_ensino,
			tp_estado_civil,
			tp_cor_raca,
			in_baixa_visao,
			in_cegueira,
			in_surdez,
			in_deficiencia_auditiva,
			in_surdo_cegueira,
			in_deficiencia_fisica,
			in_deficiencia_mental,
			in_deficit_atencao,
			in_dislexia,
			in_gestante,
			in_lactante,
			in_idoso,
			in_autismo,
			in_sabatista,
			in_braille,
			in_ampliada_24,
			in_ampliada_18,
			in_ledor,
			in_acesso,
			in_transcricao,
			in_libras,
			in_leitura_labial,
			in_mesa_cadeira_rodas,
			in_mesa_cadeira_separada,
			in_guia_interprete,
			in_certificado,
			cod_municipio_prova,
			nota_cn,
			nota_ch,
			nota_lc,
			nota_mt,
			nu_nota_comp1,
			nu_nota_comp2,
			nu_nota_comp3,
			nu_nota_comp4,
			nu_nota_comp5,
			nu_nota_redacao,
			case when q02='A' then 'B' when q02='B' then 'C' when q02='C' then 'E'
			when q02='D' then 'G' when q02='E' or q02='F' or q02='G' then 'H'
			when q02='H' then 'A' else q02 end as q001,
			case when q03='A' then 'B' when q03='B' then 'C' when q03='C' then 'E'
			when q03='D' then 'G' when q03='E' or q03='F' or q03='G' then 'H'
			when q03='H' then 'A' else q03 end as q002,
			NULL as q003,
			NULL as q004,
			case when q06='B' then 'C' when q06='C' then 'D' else q06 end as q005,
			q07 as q006,
			NULL as q007,
			NULL as q008,
			NULL as q009,
			NULL as q010,
			NULL as q011,
			NULL as q012,
			NULL as q013,
			NULL as q014,
			NULL as q015,
			NULL as q016,
			NULL as q017,
			NULL as q018,
			NULL as q019,
			NULL as q020,
			NULL as q021,
			case when q08='B' then 'C' else q08 end as q022,
			q24 as q023,
			NULL as q024,
			NULL as q025,
			NULL as q026,
			NULL as q027,
			q27 as q028,
			NULL as q029,
			q28 as q030,
			q29 as q031,
			case when q30='F' then NULL when q30='H' then NULL else q30 end as q032,
			q31 as q033,
			q32 as q034,
			case when q33='F' then NULL when q33='H' then NULL else q33 end as q035,
			NULL as q036,
			NULL as q037,
			NULL as q038,
			NULL as q039,
			NULL as q040,
			q22 as q041,
			q09 as q042,
			q10 as q043,
			q11 as q044,
			q12 as q045,
			q13 as q046,
			q15 as q047,
			q16 as q048,
			q17 as q049,
			q18 as q050,
			q19 as q051,
			q20 as q052,
			q21 as q053,
			q34 as q054,
			q35 as q055,
			q36 as q056,
			q37 as q057,
			q38 as q058,
			q39 as q059,
			q40 as q060,
			q41 as q061,
			NULL as q062,
			NULL as q063,
			q44 as q064,
			case when q45 in (0,1,2) then 'A' when q45 in (3,4,5) then 'B' else NULL end as q065,
			case when q46 in (0,1,2) then 'A' when q46 in (3,4,5) then 'B' else NULL end as q066,
			NULL as q067,
			case when q47 in (0,1,2) then 'A' when q47 in (3,4,5) then 'B' else NULL end as q068,
			NULL as q069,
			case when q48 in (0,1,2) then 'A' when q48 in (3,4,5) then 'B' else NULL end as q070,
			case when q49 in (0,1,2) then 'A' when q49 in (3,4,5) then 'B' else NULL end as q071,
			case when q50 in (0,1,2) then 'A' when q50 in (3,4,5) then 'B' else NULL end as q072,
			case when q51 in (0,1,2) then 'A' when q51 in (3,4,5) then 'B' else NULL end as q073,
			case when q52 in (0,1,2) then 'A' when q52 in (3,4,5) then 'B' else NULL end as q074,
			NULL as q075,
			q53 as q076
			FROM enem_2010
			WHERE q02 is not null and nota_cn is not null and nota_ch is not null and nota_lc is not null and nota_mt is not null and nu_nota_comp1 is not null and nu_nota_comp2 is not null and nu_nota_comp3 is not null and nu_nota_comp4 is not null and nu_nota_comp5 is not null and nu_nota_redacao is not null
		),

		alunos_2010 as(
				select 	distinct 
						t1.co_aluno,
						t1.nu_cpf,
						t1.co_ies,
						t2.ds_categoria_administrativa,
						t2.ds_organizacao_academica,
						t1.co_curso,
						extract(year from dt_ingresso_curso) as ano_ing,
						case when extract(month from dt_ingresso_curso)<=6 then 1 else 2 end as semestre_ingresso,
						COALESCE(t2.qt_vagas_integral_pres,0) + COALESCE(t2.qt_vagas_matutino_pres,0) + COALESCE(t2.qt_vagas_noturno_pres,0) + COALESCE(t2.qt_vagas_vespertino_pres,0) as vagas,					
						COALESCE(t2.qt_inscritos_integral_pres,0) + COALESCE(t2.qt_inscritos_matutino_pres,0) + COALESCE(t2.qt_inscritos_noturno_pres,0) + COALESCE(t2.qt_inscritos_vespertino_pres,0) as candidatos, 	
						co_ocde_area_geral,
						case when co_ocde_area_geral in (4,5) then 1 /*Exatas*/
							 when co_ocde_area_geral in (6,7) then 2 /*Saude*/
							 when co_ocde_area_geral in (1,2,3,8) then 3 /*Humanas*/
						end as areas_3,
						tp_atributo_ingresso as ABI,
						in_integral_curso,
						in_matutino_curso,
						in_vespertino_curso,
						in_noturno_curso,
						nu_integralizacao_integral,
						nu_integralizacao_matutino,
						nu_integralizacao_vespertino,
						nu_integralizacao_noturno,
						co_nacionalidade_aluno,
						co_aluno_situacao,
						in_reserva_vagas,
						in_compl_estagio,
						in_compl_extensao,
						in_compl_monitoria,
						in_compl_pesquisa,
						in_bolsa_estagio,
						in_bolsa_monitoria,
						in_bolsa_pesquisa,
						in_bolsa_extensao,
						count(t1.co_curso) over (partition by co_aluno) as num_cursos,
						2010 as ano
				from dm_aluno_2010 t1
				inner join dm_curso_2010 t2 on t1.co_curso=t2.co_curso
				where t1.co_modalidade_ensino=1 and t1.co_nivel_academico=1
					and extract(year from dt_ingresso_curso)=2010 and not(co_aluno_situacao=5 and tp_atributo_ingresso=1)
					and ",paste0("t1.co_ies in (",paste(co_ies,collapse=","),")"),"
		),

		num_ies_2010 as (
		select 	count(distinct co_ies) as num_ies,
				co_aluno
		from dm_aluno_2010
		group by co_aluno
		),

		docentes_2010 as (
			select	distinct 
					co_curso,
					count(case when co_situacao_docente=1 then 1 end) over (partition by t1.co_curso) as doc_exercicio,
					count(case when co_situacao_docente=2 then 1 end) over (partition by t1.co_curso) as doc_qualifcacao,
					count(case when co_situacao_docente=3 then 1 end) over (partition by t1.co_curso) as doc_exer_outro_org,
					count(case when co_situacao_docente=4 then 1 end) over (partition by t1.co_curso) as doc_afastado_outro,
					count(case when co_situacao_docente=5 then 1 end) over (partition by t1.co_curso) as doc_afas_saude,
					count(case when co_escolaridade_docente=1 then 1 end) over (partition by t1.co_curso) as doc_sem_grad,
					count(case when co_escolaridade_docente=2 then 1 end) over (partition by t1.co_curso) as doc_graduacao,
					count(case when co_escolaridade_docente=3 then 1 end) over (partition by t1.co_curso) as doc_especializacao,
					count(case when co_escolaridade_docente=4 then 1 end) over (partition by t1.co_curso) as doc_mestrado,
					count(case when co_escolaridade_docente=5 then 1 end) over (partition by t1.co_curso) as doc_doutorado,
					count(case when co_regime_trabalho=1 then 1 end) over (partition by t1.co_curso) as doc_integ_de,
					count(case when co_regime_trabalho=2 then 1 end) over (partition by t1.co_curso) as doc_integ_sem_de,
					count(case when co_regime_trabalho=3 then 1 end) over (partition by t1.co_curso) as doc_temp_parcial,
					count(case when co_regime_trabalho=4 then 1 end) over (partition by t1.co_curso) as doc_horista,
					count(case when co_nacionalidade_docente=1 then 1 end) over (partition by t1.co_curso) as doc_brasileiro,
					count(case when co_nacionalidade_docente=2 then 1 end) over (partition by t1.co_curso) as doc_brasileiro_nat,
					count(case when co_nacionalidade_docente=3 then 1 end) over (partition by t1.co_curso) as doc_estrangeiro
			from docente_curso_2010 t1 
			inner join dm_docente_2010 t2 on t1.co_docente=t2.co_docente
			where co_curso in (select co_curso from alunos_2010)
		),

		alunos_2011 as (
			select 	distinct 
					t1.co_aluno,
					t1.nu_cpf,
					t1.co_ies,
					t2.ds_categoria_administrativa,
					t2.ds_organizacao_academica,
					t1.co_curso,
					extract(year from dt_ingresso_curso) as ano_ing,
					case when extract(month from dt_ingresso_curso)<=6 then 1 else 2 end as semestre_ingresso,
					COALESCE(t2.qt_vagas_integral_pres,0) + COALESCE(t2.qt_vagas_matutino_pres,0) + COALESCE(t2.qt_vagas_noturno_pres,0) + COALESCE(t2.qt_vagas_vespertino_pres,0) as vagas,					
					COALESCE(t2.qt_inscritos_integral_pres,0) + COALESCE(t2.qt_inscritos_matutino_pres,0) + COALESCE(t2.qt_inscritos_noturno_pres,0) + COALESCE(t2.qt_inscritos_vespertino_pres,0) as candidatos, 	
					co_ocde_area_geral,
					case when co_ocde_area_geral in (4,5) then 1 /*Exatas*/
						 when co_ocde_area_geral in (6,7) then 2 /*Saude*/
						 when co_ocde_area_geral in (1,2,3,8) then 3 /*Humanas*/
					end as areas_3,
					tp_atributo_ingresso as ABI,
					in_integral_curso,
					in_matutino_curso,
					in_vespertino_curso,
					in_noturno_curso,
					nu_integralizacao_integral,
					nu_integralizacao_matutino,
					nu_integralizacao_vespertino,
					nu_integralizacao_noturno,
					co_nacionalidade_aluno,
					co_aluno_situacao,
					in_reserva_vagas,
					in_compl_estagio,
					in_compl_extensao,
					in_compl_monitoria,
					in_compl_pesquisa,
					in_bolsa_estagio,
					in_bolsa_monitoria,
					in_bolsa_pesquisa,
					in_bolsa_extensao,
					count(t1.co_curso) over (partition by co_aluno) as num_cursos,
					2011 as ano
			from dm_aluno_2011 t1
			inner join dm_curso_2011 t2 on t1.co_curso=t2.co_curso
			where t1.co_modalidade_ensino=1 and t1.co_nivel_academico=1
				and extract(year from dt_ingresso_curso)=2011 and not(co_aluno_situacao=5 and tp_atributo_ingresso=1)
				and ",paste0("t1.co_ies in (",paste(co_ies,collapse=","),")"),"
		),

		num_ies_2011 as (
		select 	count(distinct co_ies) as num_ies,
				co_aluno
		from dm_aluno_2011
		group by co_aluno
		),

		docentes_2011 as (
			select	distinct 
					co_curso,
					count(case when co_situacao_docente=1 then 1 end) over (partition by t1.co_curso) as doc_exercicio,
					count(case when co_situacao_docente=2 then 1 end) over (partition by t1.co_curso) as doc_qualifcacao,
					count(case when co_situacao_docente=3 then 1 end) over (partition by t1.co_curso) as doc_exer_outro_org,
					count(case when co_situacao_docente=4 then 1 end) over (partition by t1.co_curso) as doc_afastado_outro,
					count(case when co_situacao_docente=5 then 1 end) over (partition by t1.co_curso) as doc_afas_saude,
					count(case when co_escolaridade_docente=1 then 1 end) over (partition by t1.co_curso) as doc_sem_grad,
					count(case when co_escolaridade_docente=2 then 1 end) over (partition by t1.co_curso) as doc_graduacao,
					count(case when co_escolaridade_docente=3 then 1 end) over (partition by t1.co_curso) as doc_especializacao,
					count(case when co_escolaridade_docente=4 then 1 end) over (partition by t1.co_curso) as doc_mestrado,
					count(case when co_escolaridade_docente=5 then 1 end) over (partition by t1.co_curso) as doc_doutorado,
					count(case when co_regime_trabalho=1 then 1 end) over (partition by t1.co_curso) as doc_integ_de,
					count(case when co_regime_trabalho=2 then 1 end) over (partition by t1.co_curso) as doc_integ_sem_de,
					count(case when co_regime_trabalho=3 then 1 end) over (partition by t1.co_curso) as doc_temp_parcial,
					count(case when co_regime_trabalho=4 then 1 end) over (partition by t1.co_curso) as doc_horista,
					count(case when co_nacionalidade_docente=1 then 1 end) over (partition by t1.co_curso) as doc_brasileiro,
					count(case when co_nacionalidade_docente=2 then 1 end) over (partition by t1.co_curso) as doc_brasileiro_nat,
					count(case when co_nacionalidade_docente=3 then 1 end) over (partition by t1.co_curso) as doc_estrangeiro
			from docente_curso_2011 t1 
			inner join dm_docente_2011 t2 on t1.co_docente=t2.co_docente
			where co_curso in (select co_curso from alunos_2011)
		),
			
		alunos_2012 as (
			select 	distinct 
					t1.co_aluno,
					t1.nu_cpf,
					t1.co_ies,
					t2.ds_categoria_administrativa,
					t2.ds_organizacao_academica,
					t1.co_curso,
					extract(year from dt_ingresso_curso) as ano_ing,
					case when extract(month from dt_ingresso_curso)<=6 then 1 else 2 end as semestre_ingresso,
					COALESCE(t2.qt_vagas_integral_pres,0) + COALESCE(t2.qt_vagas_matutino_pres,0) + COALESCE(t2.qt_vagas_noturno_pres,0) + COALESCE(t2.qt_vagas_vespertino_pres,0) as vagas,					
					COALESCE(t2.qt_inscritos_integral_pres,0) + COALESCE(t2.qt_inscritos_matutino_pres,0) + COALESCE(t2.qt_inscritos_noturno_pres,0) + COALESCE(t2.qt_inscritos_vespertino_pres,0) as candidatos, 	
					co_ocde_area_geral,
					case when co_ocde_area_geral in (4,5) then 1 /*Exatas*/
						 when co_ocde_area_geral in (6,7) then 2 /*Saude*/
						 when co_ocde_area_geral in (1,2,3,8) then 3 /*Humanas*/
					end as areas_3,
					tp_atributo_ingresso as ABI,
					in_integral_curso,
					in_matutino_curso,
					in_vespertino_curso,
					in_noturno_curso,
					nu_integralizacao_integral,
					nu_integralizacao_matutino,
					nu_integralizacao_vespertino,
					nu_integralizacao_noturno,
					co_nacionalidade_aluno,
					co_aluno_situacao,
					in_reserva_vagas,
					in_compl_estagio,
					in_compl_extensao,
					in_compl_monitoria,
					in_compl_pesquisa,
					in_bolsa_estagio,
					in_bolsa_monitoria,
					in_bolsa_pesquisa,
					in_bolsa_extensao,
					count(t1.co_curso) over (partition by co_aluno) as num_cursos,
					2012 as ano
			from dm_aluno_2012 t1
			inner join dm_curso_2012 t2 on t1.co_curso=t2.co_curso
			where t1.co_modalidade_ensino=1 and t1.co_nivel_academico=1
				and extract(year from dt_ingresso_curso)=2012 and not(co_aluno_situacao=5 and tp_atributo_ingresso=1)
				and ",paste0("t1.co_ies in (",paste(co_ies,collapse=","),")"),"
		),

		num_ies_2012 as (
				select 	count(distinct co_ies) as num_ies,
						co_aluno
				from dm_aluno_2012
				group by co_aluno
		),

		docentes_2012 as (
			select	distinct 
					co_curso,
					count(case when co_situacao_docente=1 then 1 end) over (partition by t1.co_curso) as doc_exercicio,
					count(case when co_situacao_docente=2 then 1 end) over (partition by t1.co_curso) as doc_qualifcacao,
					count(case when co_situacao_docente=3 then 1 end) over (partition by t1.co_curso) as doc_exer_outro_org,
					count(case when co_situacao_docente=4 then 1 end) over (partition by t1.co_curso) as doc_afastado_outro,
					count(case when co_situacao_docente=5 then 1 end) over (partition by t1.co_curso) as doc_afas_saude,
					count(case when co_escolaridade_docente=1 then 1 end) over (partition by t1.co_curso) as doc_sem_grad,
					count(case when co_escolaridade_docente=2 then 1 end) over (partition by t1.co_curso) as doc_graduacao,
					count(case when co_escolaridade_docente=3 then 1 end) over (partition by t1.co_curso) as doc_especializacao,
					count(case when co_escolaridade_docente=4 then 1 end) over (partition by t1.co_curso) as doc_mestrado,
					count(case when co_escolaridade_docente=5 then 1 end) over (partition by t1.co_curso) as doc_doutorado,
					count(case when co_regime_trabalho=1 then 1 end) over (partition by t1.co_curso) as doc_integ_de,
					count(case when co_regime_trabalho=2 then 1 end) over (partition by t1.co_curso) as doc_integ_sem_de,
					count(case when co_regime_trabalho=3 then 1 end) over (partition by t1.co_curso) as doc_temp_parcial,
					count(case when co_regime_trabalho=4 then 1 end) over (partition by t1.co_curso) as doc_horista,
					count(case when co_nacionalidade_docente=1 then 1 end) over (partition by t1.co_curso) as doc_brasileiro,
					count(case when co_nacionalidade_docente=2 then 1 end) over (partition by t1.co_curso) as doc_brasileiro_nat,
					count(case when co_nacionalidade_docente=3 then 1 end) over (partition by t1.co_curso) as doc_estrangeiro
			from docente_curso_2012 t1 
			inner join dm_docente_2012 t2 on t1.co_docente=t2.co_docente
			where co_curso in (select co_curso from alunos_2012)
		),

		alunos_2013 as (
			select 	distinct 
					t1.co_aluno,
					t1.nu_cpf,
					t1.co_ies,
					t2.ds_categoria_administrativa,
					t2.ds_organizacao_academica,
					t1.co_curso,
					extract(year from dt_ingresso_curso) as ano_ing,
					case when extract(month from dt_ingresso_curso)<=6 then 1 else 2 end as semestre_ingresso,
					COALESCE(t2.qt_vagas_principal_integral,0) + COALESCE(t2.qt_vagas_principal_matutino,0) + COALESCE(t2.qt_vagas_principal_noturno,0) + COALESCE(t2.qt_vagas_principal_vespertino,0) as vagas,
					COALESCE(t2.qt_inscritos_principal_matu,0) + COALESCE(t2.qt_inscritos_principal_vesp,0) + COALESCE(t2.qt_inscritos_principal_noturno,0) + COALESCE(t2.qt_inscritos_principal_inte,0) as candidatos, 
					t1.co_ocde_area_geral,
					case when t1.co_ocde_area_geral in (4,5) then 1 /*Exatas*/
						 when t1.co_ocde_area_geral in (6,7) then 2 /*Saude*/
						 when t1.co_ocde_area_geral in (1,2,3,8) then 3 /*Humanas*/
					end as areas_3,
					tp_atributo_ingresso as ABI,
					in_integral_curso,
					in_matutino_curso,
					in_vespertino_curso,
					in_noturno_curso,
					nu_integralizacao_integral,
					nu_integralizacao_matutino,
					nu_integralizacao_vespertino,
					nu_integralizacao_noturno,
					co_nacionalidade_aluno,
					co_aluno_situacao,
					in_reserva_vagas,
					in_compl_estagio,
					in_compl_extensao,
					in_compl_monitoria,
					in_compl_pesquisa,
					in_bolsa_estagio,
					in_bolsa_monitoria,
					in_bolsa_pesquisa,
					in_bolsa_extensao,
					count(t1.co_curso) over (partition by co_aluno) as num_cursos,
					2013 as ano
			from dm_aluno_2013 t1
			inner join dm_curso_2013 t2 on t1.co_curso=t2.co_curso
			where t1.co_modalidade_ensino=1 and t1.co_nivel_academico=1
				and extract(year from dt_ingresso_curso)=2013 and not(co_aluno_situacao=5 and tp_atributo_ingresso=1)
				and ",paste0("t1.co_ies in (",paste(co_ies,collapse=","),")"),"
		),

		num_ies_2013 as (
			select 	count(distinct co_ies) as num_ies,
					co_aluno
			from dm_aluno_2013
			group by co_aluno
		),

		docentes_2013 as (
			select	distinct 
					co_curso,
					count(case when co_situacao_docente=1 then 1 end) over (partition by t1.co_curso) as doc_exercicio,
					count(case when co_situacao_docente=2 then 1 end) over (partition by t1.co_curso) as doc_qualifcacao,
					count(case when co_situacao_docente=3 then 1 end) over (partition by t1.co_curso) as doc_exer_outro_org,
					count(case when co_situacao_docente=4 then 1 end) over (partition by t1.co_curso) as doc_afastado_outro,
					count(case when co_situacao_docente=5 then 1 end) over (partition by t1.co_curso) as doc_afas_saude,
					count(case when co_escolaridade_docente=1 then 1 end) over (partition by t1.co_curso) as doc_sem_grad,
					count(case when co_escolaridade_docente=2 then 1 end) over (partition by t1.co_curso) as doc_graduacao,
					count(case when co_escolaridade_docente=3 then 1 end) over (partition by t1.co_curso) as doc_especializacao,
					count(case when co_escolaridade_docente=4 then 1 end) over (partition by t1.co_curso) as doc_mestrado,
					count(case when co_escolaridade_docente=5 then 1 end) over (partition by t1.co_curso) as doc_doutorado,
					count(case when co_regime_trabalho=1 then 1 end) over (partition by t1.co_curso) as doc_integ_de,
					count(case when co_regime_trabalho=2 then 1 end) over (partition by t1.co_curso) as doc_integ_sem_de,
					count(case when co_regime_trabalho=3 then 1 end) over (partition by t1.co_curso) as doc_temp_parcial,
					count(case when co_regime_trabalho=4 then 1 end) over (partition by t1.co_curso) as doc_horista,
					count(case when co_nacionalidade_docente=1 then 1 end) over (partition by t1.co_curso) as doc_brasileiro,
					count(case when co_nacionalidade_docente=2 then 1 end) over (partition by t1.co_curso) as doc_brasileiro_nat,
					count(case when co_nacionalidade_docente=3 then 1 end) over (partition by t1.co_curso) as doc_estrangeiro
			from docente_curso_2013 t1 
			inner join dm_docente_2013 t2 on t1.co_docente=t2.co_docente
			where co_curso in (select co_curso from alunos_2013)
		),


		alunos_2014 as (
			select 	distinct 
					t1.co_aluno,
					t1.nu_cpf,
					t1.co_ies,
					t2.ds_categoria_administrativa,
					t2.ds_organizacao_academica,
					t1.co_curso,
					extract(year from dt_ingresso_curso) as ano_ing,
					case when extract(month from dt_ingresso_curso)<=6 then 1 else 2 end as semestre_ingresso,
					COALESCE(t2.qt_vagas_novas_integral,0) + COALESCE(t2.qt_vagas_novas_matutino,0) + COALESCE(t2.qt_vagas_novas_vespertino,0) + COALESCE(t2.qt_vagas_novas_noturno,0) as vagas,
					COALESCE(t2.qt_insc_vagas_novas_int,0) + COALESCE(t2.qt_insc_vagas_novas_mat,0) + COALESCE(t2.qt_insc_vagas_novas_vesp,0) + COALESCE(t2.qt_insc_vagas_novas_not,0) as candidatos, 
					t1.co_ocde_area_geral,
					case when t1.co_ocde_area_geral in (4,5) then 1 /*Exatas*/
						 when t1.co_ocde_area_geral in (6,7) then 2 /*Saude*/
						 when t1.co_ocde_area_geral in (1,2,3,8) then 3 /*Humanas*/
					end as areas_3,
					tp_atributo_ingresso as ABI,
					in_integral_curso,
					in_matutino_curso,
					in_vespertino_curso,
					in_noturno_curso,
					nu_integralizacao_integral,
					nu_integralizacao_matutino,
					nu_integralizacao_vespertino,
					nu_integralizacao_noturno,
					co_nacionalidade_aluno,
					co_aluno_situacao,
					in_reserva_vagas,
					in_compl_estagio,
					in_compl_extensao,
					in_compl_monitoria,
					in_compl_pesquisa,
					in_bolsa_estagio,
					in_bolsa_monitoria,
					in_bolsa_pesquisa,
					in_bolsa_extensao,
					count(t1.co_curso) over (partition by co_aluno) as num_cursos,
					2014 as ano
			from dm_aluno_2014 t1
			inner join dm_curso_2014 t2 on t1.co_curso=t2.co_curso
			where t1.co_modalidade_ensino=1 and t1.co_nivel_academico=1
				and extract(year from dt_ingresso_curso)=2014 and not(co_aluno_situacao=5 and tp_atributo_ingresso=1)
				and ",paste0("t1.co_ies in (",paste(co_ies,collapse=","),")"),"
		),

		num_ies_2014 as (
			select 	count(distinct co_ies) as num_ies,
					co_aluno
			from dm_aluno_2014
			group by co_aluno
		),

		docentes_2014 as (
			select	distinct 
					co_curso,
					count(case when co_situacao_docente=1 then 1 end) over (partition by t1.co_curso) as doc_exercicio,
					count(case when co_situacao_docente=2 then 1 end) over (partition by t1.co_curso) as doc_qualifcacao,
					count(case when co_situacao_docente=3 then 1 end) over (partition by t1.co_curso) as doc_exer_outro_org,
					count(case when co_situacao_docente=4 then 1 end) over (partition by t1.co_curso) as doc_afastado_outro,
					count(case when co_situacao_docente=5 then 1 end) over (partition by t1.co_curso) as doc_afas_saude,
					count(case when co_escolaridade_docente=1 then 1 end) over (partition by t1.co_curso) as doc_sem_grad,
					count(case when co_escolaridade_docente=2 then 1 end) over (partition by t1.co_curso) as doc_graduacao,
					count(case when co_escolaridade_docente=3 then 1 end) over (partition by t1.co_curso) as doc_especializacao,
					count(case when co_escolaridade_docente=4 then 1 end) over (partition by t1.co_curso) as doc_mestrado,
					count(case when co_escolaridade_docente=5 then 1 end) over (partition by t1.co_curso) as doc_doutorado,
					count(case when co_regime_trabalho=1 then 1 end) over (partition by t1.co_curso) as doc_integ_de,
					count(case when co_regime_trabalho=2 then 1 end) over (partition by t1.co_curso) as doc_integ_sem_de,
					count(case when co_regime_trabalho=3 then 1 end) over (partition by t1.co_curso) as doc_temp_parcial,
					count(case when co_regime_trabalho=4 then 1 end) over (partition by t1.co_curso) as doc_horista,
					count(case when co_nacionalidade_docente=1 then 1 end) over (partition by t1.co_curso) as doc_brasileiro,
					count(case when co_nacionalidade_docente=2 then 1 end) over (partition by t1.co_curso) as doc_brasileiro_nat,
					count(case when co_nacionalidade_docente=3 then 1 end) over (partition by t1.co_curso) as doc_estrangeiro
			from docente_curso_2014 t1 
			inner join dm_docente_2014 t2 on t1.co_docente=t2.co_docente
			where co_curso in (select co_curso from alunos_2014)
		),


		ies as (
			select	t1.*,
					doc_exercicio,
					doc_qualifcacao,
					doc_exer_outro_org,
					doc_afastado_outro,
					doc_falecido,
					doc_sem_grad,
					doc_graduacao,
					doc_especializacao,
					doc_mestrado,
					doc_doutorado,
					doc_integ_de,
					doc_integ_sem_de,
					doc_temp_parcial,
					doc_horista,
					doc_brasileiro,
					doc_brasileiro_nat,
					doc_estrangeiro
			from alunos_2010 t1
			inner join docentes_2010 t2 on t1.co_curso=t2.co_curso

			union all

			select	t1.*,
					doc_exercicio,
					doc_qualifcacao,
					doc_exer_outro_org,
					doc_afastado_outro,
					doc_falecido,
					doc_sem_grad,
					doc_graduacao,
					doc_especializacao,
					doc_mestrado,
					doc_doutorado,
					doc_integ_de,
					doc_integ_sem_de,
					doc_temp_parcial,
					doc_horista,
					doc_brasileiro,
					doc_brasileiro_nat,
					doc_estrangeiro
			from alunos_2011 t1
			inner join docentes_2011 t2 on t1.co_curso=t2.co_curso

			union all

			select	t1.*,
					doc_exercicio,
					doc_qualifcacao,
					doc_exer_outro_org,
					doc_afastado_outro,
					doc_falecido,
					doc_sem_grad,
					doc_graduacao,
					doc_especializacao,
					doc_mestrado,
					doc_doutorado,
					doc_integ_de,
					doc_integ_sem_de,
					doc_temp_parcial,
					doc_horista,
					doc_brasileiro,
					doc_brasileiro_nat,
					doc_estrangeiro
			from alunos_2012 t1
			inner join docentes_2012 t2 on t1.co_curso=t2.co_curso

			union all

			select	t1.*,
					doc_exercicio,
					doc_qualifcacao,
					doc_exer_outro_org,
					doc_afastado_outro,
					doc_falecido,
					doc_sem_grad,
					doc_graduacao,
					doc_especializacao,
					doc_mestrado,
					doc_doutorado,
					doc_integ_de,
					doc_integ_sem_de,
					doc_temp_parcial,
					doc_horista,
					doc_brasileiro,
					doc_brasileiro_nat,
					doc_estrangeiro
			from alunos_2013 t1
			inner join docentes_2013 t2 on t1.co_curso=t2.co_curso

			union all

			select	t1.*,
					doc_exercicio,
					doc_qualifcacao,
					doc_exer_outro_org,
					doc_afastado_outro,
					doc_falecido,
					doc_sem_grad,
					doc_graduacao,
					doc_especializacao,
					doc_mestrado,
					doc_doutorado,
					doc_integ_de,
					doc_integ_sem_de,
					doc_temp_parcial,
					doc_horista,
					doc_brasileiro,
					doc_brasileiro_nat,
					doc_estrangeiro
			from alunos_2014 t1
			inner join docentes_2014 t2 on t1.co_curso=t2.co_curso
		),

		",
		if(tipo_evasao=="curso"){"
			evasao as (
				select	t1.*,
						1 as evasao
				from ult_sit t1
				where co_aluno_situacao in (4,5)

				union all

				select 	t2.*,
						0 as evasao
				from ult_sit t2
				where co_aluno_situacao not in (4,5)
			)"
		}else if (tipo_evasao=="ies"){"
			evasao as (
				select 	tab1.*,
						1 as evasao		
				from(
					select 	t1.*,
							count(co_curso) over (partition by co_aluno,co_ies) as num_cursos,
							count(case when co_aluno_situacao=4 then 1 end) over (partition by co_aluno) as num_desvinc,
							count(case when co_aluno_situacao=5 then 1 end) over (partition by co_aluno) as num_transf
					from ult_sit t1
				)tab1
				where (num_desvinc=num_cursos) or (num_transf+num_desvinc = num_cursos)

				union all

				select	tab2.*,
						0 as evasao		
				from(
					select 	t2.*,
							count(co_curso) over (partition by co_aluno) as num_cursos,
							count(case when co_aluno_situacao=4 then 1 end) over (partition by co_aluno) as num_desvinc,
							count(case when co_aluno_situacao=5 then 1 end) over (partition by co_aluno) as num_transf
					from ult_sit t2
				)tab2
				where not((num_desvinc=num_cursos) or (num_transf+num_desvinc = num_cursos))
			)"
		}else if(tipo_evasao=="grupo"){"
			evasao as (
				select 	tab1.*,
						1 as evasao		
				from(
					select 	t1.*,
							count(co_ocde_area_geral) over (partition by co_aluno) as num_grupos,
							count(case when co_aluno_situacao=4 then 1 end) over (partition by co_aluno) as num_desvinc,
							count(case when co_aluno_situacao=5 then 1 end) over (partition by co_aluno) as num_transf
					from ult_sit t1
				)tab1
				where (num_desvinc=num_grupos) or (num_transf+num_desvinc = num_grupos)

				union all

				select 	tab2.*,
						0 as evasao		
				from(
					select 	t2.*,
							count(co_ocde_area_geral) over (partition by co_aluno) as num_grupos,
							count(case when co_aluno_situacao=4 then 1 end) over (partition by co_aluno) as num_desvinc,
							count(case when co_aluno_situacao=5 then 1 end) over (partition by co_aluno) as num_transf
					from ult_sit t2
				)tab2
				where not((num_desvinc=num_grupos) or (num_transf+num_desvinc = num_grupos))
			)"
		},"

		select 	tab2.co_ies,
			tab2.co_curso,
			tab2.semestre_ingresso,
			tab2.vagas,
			tab2.candidatos, 
			tab2.co_grau_academico,
			tab2.co_nivel_academico,
			tab2.co_ocde_area_geral,
			tab2.areas_3,
			tab2.ABI,
			tab2.in_integral_curso,
			tab2.in_matutino_curso,
			tab2.in_vespertino_curso,
			tab2.in_noturno_curso,
			tab2.nu_integralizacao_integral,
			tab2.nu_integralizacao_matutino,
			tab2.nu_integralizacao_vespertino,
			tab2.nu_integralizacao_noturno,
			tab2.co_nacionalidade_aluno,
			tab2.co_aluno_situacao,
			tab2.in_reserva_vagas,
			tab2.in_bolsa_estagio,
			tab2.in_bolsa_monitoria,
			tab2.in_bolsa_pesquisa,
			tab2.in_bolsa_extensao,
			tab2.num_ies,
			tab2.ano_max,
			tab2.evasao,
			tab2.doc_exercicio,
			tab2.doc_qualifcacao,
			tab2.doc_exer_outro_org,
			tab2.doc_afastado_outro,
			tab2.doc_falecido,
			tab2.doc_sem_grad,
			tab2.doc_graduacao,
			tab2.doc_especializacao,
			tab2.doc_mestrado,
			tab2.doc_doutorado,
			tab2.doc_integ_de,
			tab2.doc_integ_sem_de,
			tab2.doc_temp_parcial,
			tab2.doc_horista,
			tab2.doc_brasileiro,
			tab2.doc_brasileiro_nat,
			tab2.doc_estrangeiro,
			--atributos ENEM
			tab2.in_estuda_classe_hospitalar,
			tab2.cod_municipio_residencia,
			tab2.cod_municipio_esc,
			tab2.id_dependencia_adm_esc,
			tab2.id_localizacao_esc,
			tab2.sit_func_esc,
			tab2.idade,
			tab2.tp_sexo,
			tab2.nacionalidade,
			tab2.cod_municipio_nascimento,
			tab2.st_conclusao,
			tab2.ano_concluiu,
			tab2.tp_escola,
			tab2.in_tp_ensino,
			tab2.tp_estado_civil,
			tab2.tp_cor_raca,
			tab2.in_baixa_visao,
			tab2.in_cegueira,
			tab2.in_surdez,
			tab2.in_deficiencia_auditiva,
			tab2.in_surdo_cegueira,
			tab2.in_deficiencia_fisica,
			tab2.in_deficiencia_mental,
			tab2.in_deficit_atencao,
			tab2.in_dislexia,
			tab2.in_gestante,
			tab2.in_lactante,
			tab2.in_idoso,
			tab2.in_autismo,
			tab2.in_sabatista,
			tab2.in_braille,
			tab2.in_ampliada_24,
			tab2.in_ampliada_18,
			tab2.in_ledor,
			tab2.in_acesso,
			tab2.in_transcricao,
			tab2.in_libras,
			tab2.in_leitura_labial,
			tab2.in_mesa_cadeira_rodas,
			tab2.in_mesa_cadeira_separada,
			tab2.in_guia_interprete,
			tab2.in_certificado,
			tab2.cod_municipio_prova,
			tab2.nu_nota_comp1,
			tab2.nu_nota_comp2,
			tab2.nu_nota_comp3,
			tab2.nu_nota_comp4,
			tab2.nu_nota_comp5,
			tab2.nu_nota_redacao,
			tab2.q001,
			tab2.q002,
			tab2.q003,
			tab2.q004,
			tab2.q005,
			tab2.q006,
			tab2.q007,
			tab2.q008,
			tab2.q009,
			tab2.q010,
			tab2.q011,
			tab2.q012,
			tab2.q013,
			tab2.q014,
			tab2.q015,
			tab2.q016,
			tab2.q017,
			tab2.q018,
			tab2.q019,
			tab2.q020,
			tab2.q021,
			tab2.q022,
			tab2.q023,
			tab2.q024,
			tab2.q025,
			tab2.q026,
			tab2.q027,
			tab2.q028,
			tab2.q029,
			tab2.q030,
			tab2.q031,
			tab2.q032,
			tab2.q033,
			tab2.q034,
			tab2.q035,
			tab2.q036,
			tab2.q037,
			tab2.q038,
			tab2.q039,
			tab2.q040,
			tab2.q041,
			tab2.q042,
			tab2.q043,
			tab2.q044,
			tab2.q045,
			tab2.q046,
			tab2.q047,
			tab2.q048,
			tab2.q049,
			tab2.q050,
			tab2.q051,
			tab2.q052,
			tab2.q053,
			tab2.q054,
			tab2.q055,
			tab2.q056,
			tab2.q057,
			tab2.q058,
			tab2.q059,
			tab2.q060,
			tab2.q061,
			tab2.q062,
			tab2.q063,
			tab2.q064,
			tab2.q065,
			tab2.q066,
			tab2.q067,
			tab2.q068,
			tab2.q069,
			tab2.q070,
			tab2.q071,
			tab2.q072,
			tab2.q073,
			tab2.q074,
			tab2.q075,
			tab2.q076
		from(
			select	distinct 
					tab.*,
					--enem_empilhado
					t2.nu_ano,
					t2.id_inscricao,
					t2.id_mascara,
					t2.in_estuda_classe_hospitalar,
					t2.cod_municipio_residencia,
					t2.cod_municipio_esc,
					t2.id_dependencia_adm_esc,
					t2.id_localizacao_esc,
					t2.sit_func_esc,
					t2.idade,
					t2.tp_sexo,
					t2.nacionalidade,
					t2.cod_municipio_nascimento,
					t2.st_conclusao,
					t2.ano_concluiu,
					t2.tp_escola,
					t2.in_tp_ensino,
					t2.tp_estado_civil,
					t2.tp_cor_raca,
					t2.in_baixa_visao,
					t2.in_cegueira,
					t2.in_surdez,
					t2.in_deficiencia_auditiva,
					t2.in_surdo_cegueira,
					t2.in_deficiencia_fisica,
					t2.in_deficiencia_mental,
					t2.in_deficit_atencao,
					t2.in_dislexia,
					t2.in_gestante,
					t2.in_lactante,
					t2.in_idoso,
					t2.in_autismo,
					t2.in_sabatista,
					t2.in_braille,
					t2.in_ampliada_24,
					t2.in_ampliada_18,
					t2.in_ledor,
					t2.in_acesso,
					t2.in_transcricao,
					t2.in_libras,
					t2.in_leitura_labial,
					t2.in_mesa_cadeira_rodas,
					t2.in_mesa_cadeira_separada,
					t2.in_guia_interprete,
					t2.in_certificado,
					t2.cod_municipio_prova,
					t2.nu_nota_comp1,
					t2.nu_nota_comp2,
					t2.nu_nota_comp3,
					t2.nu_nota_comp4,
					t2.nu_nota_comp5,
					t2.nu_nota_redacao,
					t2.q001,
					t2.q002,
					t2.q003,
					t2.q004,
					t2.q005,
					t2.q006,
					t2.q007,
					t2.q008,
					t2.q009,
					t2.q010,
					t2.q011,
					t2.q012,
					t2.q013,
					t2.q014,
					t2.q015,
					t2.q016,
					t2.q017,
					t2.q018,
					t2.q019,
					t2.q020,
					t2.q021,
					t2.q022,
					t2.q023,
					t2.q024,
					t2.q025,
					t2.q026,
					t2.q027,
					t2.q028,
					t2.q029,
					t2.q030,
					t2.q031,
					t2.q032,
					t2.q033,
					t2.q034,
					t2.q035,
					t2.q036,
					t2.q037,
					t2.q038,
					t2.q039,
					t2.q040,
					t2.q041,
					t2.q042,
					t2.q043,
					t2.q044,
					t2.q045,
					t2.q046,
					t2.q047,
					t2.q048,
					t2.q049,
					t2.q050,
					t2.q051,
					t2.q052,
					t2.q053,
					t2.q054,
					t2.q055,
					t2.q056,
					t2.q057,
					t2.q058,
					t2.q059,
					t2.q060,
					t2.q061,
					t2.q062,
					t2.q063,
					t2.q064,
					t2.q065,
					t2.q066,
					t2.q067,
					t2.q068,
					t2.q069,
					t2.q070,
					t2.q071,
					t2.q072,
					t2.q073,
					t2.q074,
					t2.q075,
					t2.q076,
					max(t2.nu_ano) over (partition by t2.nu_cpf) as ano_max2
			from evasao tab
			inner join enem_empilhado t2 on tab.nu_cpf=t2.nu_cpf and tab.ano>=t2.nu_ano
		) tab2
		where ano_max2=nu_ano
		)"
	))
}
